export const books = [
  {
    id: 1,
    name: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    description: 'A classic fantasy novel',
    genre: 'Fantasy',
    year: 1954,
    price: 100,
    image: 'https://placehold.jp/240x400.png',
    rating: 4.5,
    quantity: 10,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 2,
    name: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    description: 'A classic fantasy novel',
    genre: 'Fantasy',
    year: 1954,
    price: 100,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1448411209l/2573._SY475_.jpg',
    rating: 4.5,
    quantity: 10,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 3,
    name: 'The Fellowship of the Ring',
    author: 'J.R.R. Tolkien',
    description: 'A classic fantasy novel',
    genre: 'Fantasy',
    year: 1954,
    price: 100,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1448411209l/2573._SY475_.jpg',
    rating: 4.5,
    quantity: 10,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 4,
    name: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    description: 'A classic novel about racial injustice',
    genre: 'Fiction',
    year: 1960,
    price: 120,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg',
    rating: 4.27,
    quantity: 5,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 5,
    name: '1984',
    author: 'George Orwell',
    description: 'A dystopian novel',
    genre: 'Fiction',
    year: 1949,
    price: 90,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348990566l/5470.jpg',
    rating: 4.19,
    quantity: 8,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 6,
    name: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    description: 'A classic novel about teenageproblems',
    genre: 'Fiction',
    year: 1951,
    price: 110,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg',
    rating: 4.27,
    quantity: 5,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 7,
    name: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'A classic novel about the life of the Roaring Twenties',
    genre: 'Fiction',
    year: 1925,
    price: 100,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg',
    rating: 4.27,
    quantity: 5,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 8,
    name: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    description: 'A book about the history of Homo sapiens',
    genre: 'Non-Fiction',
    year: 2011,
    price: 150,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1595674531l/23692271._SY475_.jpg',
    rating: 4.45,
    quantity: 3,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 9,
    name: 'The Alchemist',
    author: 'Paulo Coelho',
    description: 'A classic novel about the life of the Alchemist',
    genre: 'Fiction',
    year: 1988,
    price: 120,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg',
    rating: 4.27,
    quantity: 5,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
  {
    id: 10,
    name: 'The Da Vinci Code',
    author: 'Dan Brown',
    description: 'A thriller novel',
    genre: 'Mystery',
    year: 2003,
    price: 110,
    image:
      'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1303252999l/968.jpg',
    rating: 3.85,
    quantity: 12,
    isAvailable: true,
    isInCart: false,
    isInWishlist: false,
  },
];
